# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_booking
    restart: always
    environment:
      MYSQL_DATABASE: bookingquerymsdb
      MYSQL_USER: bookingquerymsdb
      MYSQL_PASSWORD: bookingquerymsdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  axonserver:
    image: axoniq/axonserver:latest-dev
    container_name: axonserver
    restart: always
    ports:
      - "8024:8024"   # HTTP dashboard
      - "8124:8124"   # gRPC API
      - "8125:8125"   # monitoring
    volumes:
      - axon_data:/axonserver/data
      - axon_events:/axonserver/events
      - axon_log:/axonserver/log
      - ./config:/axonserver/config
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8024"]
      interval: 10s
      timeout: 5s
      retries: 5

  bookingms:
    build: .
    container_name: bookingms_app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - axonserver
    environment:
      SPRING_DATASOURCE_URL:              jdbc:mysql://mysql:3306/bookingquerymsdb?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME:         bookingquerymsdb
      SPRING_DATASOURCE_PASSWORD:         bookingquerymsdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM:       org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_GENERATE_DDL:            true

      AXON_AXONSERVER_SERVERS:           "axonserver:8124"
      JAVA_TOOL_OPTIONS:                 "-Daxon.axonserver.suppressDownloadMessage=true"

volumes:
  mysql_data:
  axon_data:
  axon_events:
  axon_log: