version: '3.8'

services:
  bookingms:
    build:
      context: .
      target: bookingms
    ports:
      - "8080:8080"
    depends_on:
      - axon-server
      - mysql

  handlingms:
    build:
      context: .
      target: handlingms
    ports:
      - "8081:8081"
    depends_on:
      - axon-server
      - rabbitmq

  routingms:
    build:
      context: .
      target: routingms
    ports:
      - "8082:8082"
    depends_on:
      - axon-server

  trackingms:
    build:
      context: .
      target: trackingms
    ports:
      - "8083:8083"
    depends_on:
      - axon-server

  axon-server:
    image: axoniq/axonserver:latest
    ports:
      - "8024:8024"
      - "8124:8124"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"