version: '3.8'

services:
  mysql_booking:
    image: mysql:8.0
    container_name: mysql_booking
    restart: always
    environment:
      MYSQL_DATABASE: bookingquerymsdb
      MYSQL_USER: bookingquerymsdb
      MYSQL_PASSWORD: bookingquerymsdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_booking_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_routing:
    image: mysql:8.0
    container_name: mysql_routing
    restart: always
    environment:
      MYSQL_DATABASE: routingmsdb
      MYSQL_USER: routingmsdb
      MYSQL_PASSWORD: routingmsdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_routing_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  axonserver:
    image: axoniq/axonserver:latest-dev
    container_name: axonserver
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8125:8125"
    volumes:
      - axon_data:/axonserver/data
      - axon_events:/axonserver/events
      - axon_log:/axonserver/log
      - ./config:/axonserver/config
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8024"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  combinedms:
    build: .
    container_name: combined_ms_app
    restart: always
    ports:
      - "8081:8081"  # bookingms
      - "8083:8083"  # routingms
    depends_on:
      mysql_booking:
        condition: service_healthy
      mysql_routing:
        condition: service_healthy
      axonserver:
        condition: service_healthy
    environment:
      # BookingMS
      BOOKING_DATASOURCE_URL: jdbc:mysql://mysql_booking:3306/bookingquerymsdb?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      BOOKING_DATASOURCE_USERNAME: bookingquerymsdb
      BOOKING_DATASOURCE_PASSWORD: bookingquerymsdb
      AXON_AXONSERVER_SERVERS: axonserver:8124
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_GENERATE_DDL: true

      # RoutingMS
      ROUTING_DATASOURCE_URL: jdbc:mysql://mysql_routing:3306/routingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      ROUTING_DATASOURCE_USERNAME: routingmsdb
      ROUTING_DATASOURCE_PASSWORD: routingmsdb
      ROUTING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL57Dialect
      ROUTING_JPA_GENERATE_DDL: true

volumes:
  mysql_booking_data:
  mysql_routing_data:
  axon_data:
  axon_events:
  axon_log:
