scrape_configs:
  - job_name: 'spring-boot-actuator'
    scrape_interval: 15s
    scrape_timeout: 10s  # tambahkan ini jika waktu default terlalu singkat
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8084']
