version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: trackingmsdb
      MYSQL_USER: trackingmsdb
      MYSQL_PASSWORD: trackingmsdb
      MYSQL_ROOT_PASSWORD: trackingmsdb
    ports:
      - "3305:3305"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3305/trackingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST
      SPRING_DATASOURCE_USERNAME: trackingmsdb
      SPRING_DATASOURCE_PASSWORD: trackingmsdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
