version: '3.8'
services:
  mysql_handling:
    image: mysql:8.0
    container_name: mysql_handling
    restart: always
    environment:
      MYSQL_DATABASE: handlingmsdb
      MYSQL_USER: handlingmsdb
      MYSQL_PASSWORD: handlingmsdb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_handling_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  handlingms:
    build: .
    container_name: handlingms_app
    ports:
      - "8082:8082"
    depends_on:
      mysql_handling:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_handling:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: handlingmsdb
      SPRING_DATASOURCE_PASSWORD: handlingmsdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_GENERATE_DDL: true
volumes:
  mysql_handling_data:
